package streams

const (
	//stream types
	STREAM_TYPE_CLIENT_BI = iota
	STREAM_TYPE_SERVER_BI

	STREAM_TYPE_CLIENT_UNI
	STREAM_TYPE_SERVER_UNI

	//stream states
	//Sending Part
	STREAM_STATE_READY
	STREAM_STATE_SEND
	STREAM_STATE_DATA_SENT
	STREAM_STATE_DATA_RECVD_SENDING
	STREAM_STATE_RESET_SENT
	STREAM_STATE_RESET_RECVD_SENDING
	//Receiving Part
	STREAM_STATE_RECV
	STREAM_STATE_SIZE_KNOWN
	STREAM_STATE_DATA_RECVD_RECVING
	STREAM_STATE_DATA_READ
	STREAM_STATE_RESET_RECVD_RECVING
	STREAM_STATE_RESET_READ
)
